### Create a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json


{
  "name" : "John Doe1102 with billing address",
  "email": "test_b1i550liling_acount1@example.com",
  "address": "123 main street212",
  "dateOfBirth": "1995-01-01",
  "registeredDate": "2025-11-28"
}

###